spring:
  application:
    name: spring-cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Vashy/SpringCloudConfigServerRepo.git
          force-pull: true
          refreshRate: 5
server:
  port: 8888

#logging:
#  level:
#    web: trace
