spring:
  application:
    name: spring-cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Vashy/SpringCloudConfigServerRepo.git
          force-pull: true
#          default-label: main
server:
  port: 8888
